//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3607
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;
using System.Configuration;
using CoreComponents.Data;

namespace CoreComponents.Data.Schema
{


	public abstract class SchemaAssembler
	{

		//protected DataSet FromSchema;
		
		protected DbDatabase ToSchema;
		
		protected SchemaRetriever Retriever; 
		
		public SchemaAssembler()
		{
		}
		
        //public virtual DbSchema Obtain()
        //{
			
        //    return Obtain(Connection.ConnectionString);
			
        //}
		
		public abstract DbDatabase Obtain();

        public string ConnectionString
        {

            get
            {

                return Retriever.ConnectionString;

            }
            set
            {

                Retriever.ConnectionString = value;

            }

        }

	}
}
